### ISSUE TITLE
Gnome notification weather not working in Pop!OS

### ISSUE THREAD

**Issue by aia832003** [pop-os/pop#126]
![gnome-correct-notifications](https://user-images.githubusercontent.com/11007827/35544753-82fc87ce-0531-11e8-860b-5af014bd2b20.png)
I am having an issue with Pop!OS not updating the Gnome weather in the notification area as expected. System information is below and I've attached screenshots of the expected result and the Pop!OS system with it not working correctly.
![gnome-incorrect-notification](https://user-images.githubusercontent.com/11007827/35544749-7cd9d388-0531-11e8-89e3-66790a8024a3.png)

**Andrew Allen**

```
 * Pop! OS - (run ```cat /etc/os-release```)
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Gnome weather in clock/calendar panel

**Issue/Bug Description**
Pop! OS does not maintain the location and present weather information.

**Steps to reproduce (if you know)**

Click weather in the panel and opens Gnome weather but doesn't update panel.

**Expected behavior**
The panel should maintain weather information and auto-update in the background via location services.

**Other Notes**

**Comment by sramkrishna** [comment]
yes, I se the same thing.  What the notification panel says and what gnome weather says are two different things.

**Comment by brs17** [comment]
@sramkrishna Can you also determine if this is an upstream issue or specifically an issue with Pop!_OS?

Thanks!

**Comment by aia832003** [comment]
I can confirm this works as intended on Fedora installations on 2 other machines. The notification applet can be manually started by changing the location manually in gnome weather instead of using location services to autoload the location.

**Comment by gregrtardif** [comment]
This is pretty old...but i found that if you turn off  automatic location within the weather app it will show up in the notification shade... so not a fix but a work around.

**Comment by juhani-korhonen** [comment]
Oh geez guys, are you serious...? Can't you just set the applet to show those locations where you actually have the weather data available...? Had to shoot blind until I found a city 115 km from where I live displaying the weather data, and I live in a University one (whereas the former is not).

And oh yeah, by this I am referring to the GNOME Weather folks, not the Pop!_OS team :-)

**Comment by BrainBlasted** [comment]
This is a gnome-shell bug, not a GNOME Weather issue. Now that it's been reported upstream, it's being looked into.

**Comment by ningfei** [comment]
See [here](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1823). Seems it has been fixed in the [upstream](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/867)

**Comment by Amazeryogo** [comment]
Try installing the flatpak version, and remove the ubuntu one, it worked for me

**Comment by FunkyMuse** [comment]
![image](https://user-images.githubusercontent.com/25645122/106372105-aae9d100-636c-11eb-8c13-e65a65f2c12e.png)

It seems that there's no schema for the saved locations if you use dconf.
The issue still remains.

**Comment by GregLumpkin** [comment]
I can verify that this is still an issue. It used to work, but stopped a while back. I have uninstalled the deb version of the weather app and installed the flatpack version and that did not fix it. I disabled auto-location, and that did not help either. The weather forecast will show data in the app if you click on the notification, but in the notification center itself, it does not show forecast information.
![Screenshot from 2021-04-16 07-44-12](https://user-images.githubusercontent.com/21108698/115112878-7f32bc00-9f55-11eb-8048-48b20e3079eb.png)

**Comment by ilteoood** [comment]
Same here on my two fresh PopOS 20.04 installations

**Comment by jacobgkau** [comment]
The issue occurring now, in 2021, is probably not the same issue that affected 17.10 in 2018, but we can use this issue page since it's still open.

It looks like this was fixed upstream: https://gitlab.gnome.org/GNOME/libgweather/-/issues/82 
It's also affecting Ubuntu, which already has an open bug report: https://bugs.launchpad.net/libgweather/+bug/1918044 

Ubuntu 20.04 and 20.10 currently ship `libgweather-3-16` version 3.36.1-1, while the issue is reportedly fixed in version 3.36.2. Debian backported the fix into version 3.36.1-3. I can confirm that after installing `libgweather-3-16` version 3.36.1-3, I have working weather in the dropdown:

![Screenshot from 2021-04-26 14-14-32](https://user-images.githubusercontent.com/7199422/116145150-29b78700-a69a-11eb-9e00-5ca81bfda53e.png)

This package comes from Ubuntu (which can be seen by running `apt policy libgweather-3-16`), so this will be fixed when Ubuntu updates their `libgweather-3-16` package to version `3.36.1-3` or higher. Alternatively, the higher `libgweather-3-16` package could be backported into Pop!_OS to replace the Ubuntu version.

In the meantime, here is a package that can be manually installed on Pop!_OS to fix the issue: https://www.dropbox.com/s/uw9agzw8iuxp1eg/libgweather-3-16_3.36.1-3_amd64.deb?dl=1 

(The download from the Debian website doesn't work because it depends on `libgdk-pixbuf-2.0-0`, while that package is called `libgdk-pixbuf2.0-0` in Ubuntu; the package I'm linking here has not been modified from [this release](https://salsa.debian.org/gnome-team/libgweather/-/tree/debian/3.36.1-3) except compiling the package on a Pop!_OS machine.)

Eddy might label this as a "downgrade," but the version number is higher and apt will not downgrade it back to Ubuntu's version (as of right now.) This does still require Location Services being enabled or selecting a location manually in the Weather app to work.

**Comment by ilteoood** [comment]
I've installed the `.deb` proposed by @jacobgkau and is working incredibly well, after a reboot!

![image](https://user-images.githubusercontent.com/6383527/116199335-4b1a8080-a737-11eb-93e1-5edb4da5e5cc.png)

Thank you so much!

**Comment by GregLumpkin** [comment]
That fixed it. Thanks!

**Comment by frafaelribeiro** [comment]
@jacobgkau Thanks!.Your `.deb` package fixed it.

**Comment by xtreitd** [comment]
This package is by default, but the weather periodically disappears. Greetings from 2022 :)
![image](https://user-images.githubusercontent.com/49349890/171598150-1fe9ff5b-7b03-4ed0-8aff-c7dbba50e51f.png)

**Comment by sahfd4eiugf** [comment]
Same issue in 2023 (now October)
The weather randomly returns 404, and thus I am unable to open the whole calendar or notification box, which is quite annoying

**Comment by leviport** [comment]
Gnome extensions do not work on COSMIC, so I think this can be closed now.
