### ISSUE TITLE
Refresh install fails with "error creating recovery partition: ... exit code: 11"

### ISSUE THREAD

**Issue by petesimonic** [pop-os/pop#1546]
Let me duplicate https://github.com/pop-os/installer/issues/218 as there no activity since APR in that repository.

**Distribution (run `cat /etc/os-release`):**
 ```console
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Refresh installation fails to update virtualized Pop-OS to boot. (Without refreshing it doesn't boot in VM. Though works perfectly in initial environment at desktop.)

**Steps to reproduce (if you know):**
1) create QCOW2 image of existing Pop-OS from 256 GB disk, which takes only 70GB (so there's plenty of space *inside the image*)
2) transfer it to another (host) system (under Pop-OS too) with 260 GB free
3) `chown` and `chmod` the image to be like native `gnome-boxes` images
4) add new VM with 12GB RAM in `gnome-boxes` and point it to the image file
5) add current Pop-OS installation ISO-image as VirtIO media
6) boot from Pop-OS installation ISO-image
7) choose to *Refresh installation*
8) receive [error in output](https://pastebin.com/kGRkbBif)

**Expected behavior:**

System boot repair.

**Other Notes:**
Tried to do <https://support.system76.com/articles/bootloader/>, but without any luck.

**Comment by jacobgkau** [comment]
As you mentioned, this is a duplicate of https://github.com/pop-os/installer/issues/218.

**Comment by petesimonic** [comment]
> As you mentioned, this is a duplicate of [pop-os/installer#218](https://github.com/pop-os/installer/issues/218).

But that repository is basically abandoned. I tried my best to identify right place to report the issue, and after two days of ignore found out that there was no activity since April!

And here you reacted same day. It's cruel. Is it possible to delete the issue from <https://github.com/pop-os/installer>? So it could be resolved just other issues here?

**Comment by jacobgkau** [comment]
@petesimonic The `installer` repository is not abandoned, it is under the `pop-os` organization (which is quite active) and it is the correct location for this issue. (If you browse the other issues in the `installer` repo, you can see that there has actually been activity there in the last week.) This `pop` repository is more of a catch-all for when users aren't sure where an issue belongs. You did the right thing by opening your issue on a likely-related component.

Please keep in mind that GitHub issues, at least in this organization, are for development-oriented bug tracking, not support requests. I'm sorry if you felt that the lack of a response after two days was "cruel," but there are a finite number of engineers working on a wide variety of projects at any given time, and timely responses to individual issues (especially ones affecting very specific use cases like this) are not guaranteed.

If you leave your other issue open, that will give it the greatest chance of being addressed when possible.

**Comment by petesimonic** [comment]
It feels like you simply minimize the number of visible issues in main repo, which quite disappointing. Few issues which are obvious to find relevant repo are easily spotted in <https://github.com/pop-os/pop/>, but they get attention, since it's the main repo. *So you by yourself create incentive not to do right thing and not to apply attention and time to create issues properly, but just post it in general repo.* 

Sorry, for being not that nice, taking into account I came here for help, and not to brag. But I'm sure this issue will be rotting there for year and a half, and will be closed like outdated because "likely resolved with a new update, doesn't reproduce". And will be reported to show how many issues you burned. As effectively no one will see this conversation -- who looks inside resolved issues -- then it's a great plan. I hope I am wrong, but it looks totally as described.

> @petesimonic The `installer` repository is not abandoned, it is under the `pop-os` organization (which is quite active) and it is the correct location for this issue. (If you browse the other issues in the `installer` repo, you can see that there has actually been activity there in the last week.) This `pop` repository is more of a catch-all for when users aren't sure where an issue belongs. You did the right thing by opening your issue on a likely-related component.

Yep, one issue, you commented, which wasn't touched for 6d. Formally maybe true, but it's not a real thing.
![image](https://user-images.githubusercontent.com/69221333/108431656-395abf80-7254-11eb-8f84-dee416950bb6.png)
> 
> Please keep in mind that GitHub issues, at least in this organization, are for development-oriented bug tracking, not support requests. I'm sorry if you felt that the lack of a response after two days was "cruel," but there are a finite number of engineers working on a wide variety of projects at any given time, and timely responses to individual issues (especially ones affecting very specific use cases like this) are not guaranteed.

Please... Stop twisting my words. You know, cruel is that you hide the issue from people who could advice something helpful. And I should notice it's not "please, tell me how do I virtualize my system" issue, but a regular bug report which address specific failure of specific feature.
> 
> If you leave your other issue open, that will give it the greatest chance of being addressed when possible.

Let us see if it will be addressed. I'm not that kind of man who try to abuse someone's repo by clicking everything possible.

**Comment by leviport** [comment]
>It feels like you simply minimize the number of visible issues in main repo, which quite disappointing.

That is not the intention at all. The Pop repo is kind of a general catch-all, and our process entails sorting issues to their appropriate repos whenever we can so they can be addressed. If anything, sorting issues into their appropriate repos gives them more visibility for them to actually be worked on. We figure that if a user has trouble finding something in a specific repo, they can still open an issue in the Pop repo, and we will then help point them in the right direction if we can. This means we either transfer the issue if it doesn't exist already, or marking as a duplicate if it does. 

I can assure you we value your prior report (https://github.com/pop-os/installer/issues/218) and we will work on it when we get a chance to.

**Comment by CSDisciple** [comment]
It's been 5 months and I'm still getting the same error, as the person who reported, when I am doing refresh install. Pop Os please fix

**Comment by N0body42** [comment]
Same issue.

**Comment by araghon007** [comment]
If you're trying to install from a USB flash drive, use balenaEtcher

**Comment by VjeraTurk** [comment]
> If you're trying to install from a USB flash drive, use balenaEtcher

Do you know what is the alternative for Linux? I had the same problem happen using UNetbootin

**Comment by VjeraTurk** [comment]
I can confirm I had the same error happen on new install while using bootable usb made with UNetbootin

**Comment by Pokey1Kenobi** [comment]
![image](https://github.com/pop-os/pop/assets/26582495/efa8c383-ab7b-46c3-a9c2-5f644e908be3)
\

**Comment by N0body42** [comment]
I just remembered when I had this issue. I used the username "Nobody" and it turns out it's a preexisting user that's  like the opposite of the root user. Maybe try installing with a different username?

**Comment by leviport** [comment]
It certainly could be VPN-related. There isn't anything information to go off of in that screenshot though. Running `pop-upgrade recovery check` might give more details.
