### ISSUE TITLE
Bluetooth not working after upgrading to kernel 5.11.0-7612-generic in Lenovo Ideapad 330 15ARR

### ISSUE THREAD

**Issue by Ldev007** [pop-os/pop#1623]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

HCI Version: 4.2 (0x8)  Revision: 0x829a
LMP Version: 4.2 (0x8)  Subversion: 0x7644
Manufacturer: Realtek Semiconductor Corporation (93)

**Issue/Bug Description:**

Cannot use bluetooth functionality until the steps defined below are done :

### TO CHECK THE CURRENT BLUETOOTH STATUS

After executing command : **systemctl status bluetooth**
Output is :
bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor pre>
     Active: active (running) since Wed 2021-04-07 14:34:17 IST; 1min 11s ago
       Docs: man:bluetoothd(8)
   Main PID: 737 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 8878)
     Memory: 1.7M
     CGroup: /system.slice/bluetooth.service
             └─737 /usr/lib/bluetooth/bluetoothd

Apr 07 14:34:17 ldevs-workstation systemd[1]: Starting Bluetooth service...
Apr 07 14:34:17 ldevs-workstation bluetoothd[737]: Bluetooth daemon 5.53
Apr 07 14:34:17 ldevs-workstation systemd[1]: Started Bluetooth service.
Apr 07 14:34:17 ldevs-workstation bluetoothd[737]: Starting SDP server
Apr 07 14:34:17 ldevs-workstation bluetoothd[737]: Bluetooth management  interface 1.19 initialized
Apr 07 14:34:17 ldevs-workstation bluetoothd[737]: Failed to set mode: Blocked through rfkill (0x12)
Apr 07 14:34:22 ldevs-workstation bluetoothd[737]: Failed to set mode: Blocked through rfkill (0x12)
Apr 07 14:34:26 ldevs-workstation bluetoothd[737]: Endpoint registered: sender=:1.71 path=/MediaEndpoint/A2DPSink/sbc
Apr 07 14:34:26 ldevs-workstation bluetoothd[737]: Endpoint registered: sender=:1.71 path=/MediaEndpoint/A2DPSource/sbc

As can be seen above **rfkill failed to set mode** because of which bluetooth couldn't turn on for which I did the following workaround: 

After executing : **rfkill unblock all** or **rfkill unblock bluetooth ; sudo systemctl restart bluetooth**
Result is : Bluetooth is unblocked by **rfkill** and **systemctl** restarts the bluetooth service which makes it turn on successfully ! if we navigate to bluetooth settings we can see **visible devices**. Close the bluetooth settings window and read below continued..

### Now, here we go for another round of issues
Remember initially after above workaround bluetooth is on and is working.
After going into **bluetooth settings** from panel like below -

![Screenshot from 2021-04-07 14-57-03](https://user-images.githubusercontent.com/47318543/113844018-b1a02480-97b1-11eb-8282-5ff244c7c718.png)

Now if you turn bluetooth toggle off and then try to turn it back on it won't turn on again also the status won't change in the panel as it should and no devices will be displayed in bluetooth settings window either.
BUT, if you close the window and then do the following -

1. Close the bluetooth settings window
2. Try to turn on bluetooth from the panel it'll turn on but status won't change still in the panel option it'll show off but you can see that sub option changed to **Turn off**. Now, click on **bluetooth settings** option again and unexpectedly the devices will show up this time.

So, mainly if you try to turn it on/off from **bluetooth settings** it won't work but if you try to do so from panel it will work. Although, the main panel bluetooth option will keep showing **off** until we navigate to **bluetooth settings** once in case when we're try turning bluetooth on/off from panel option.

Importantly, downgrading or just simply booting to **old kernel-conf** using systemd boot manager issue isn't there anymore which proves somehow that issue came up with new kernel upgrade recently.

This bug persists across rebooting the system multiple times.

**Steps to reproduce (if you know):**

To reproduce upgrade pop os v20.04 (maybe v20.10 also) to recent kernel update - **5.11.0-7612-generic**. That's all.

**Expected behavior:**

Bluetooth should turn on and off normally from both system settings as well as gnome-panel shortcut. Also, the active/inactive (ON/OFF) status of bluetooth must also reflect normally in both system settings as well as in gnome-panel.

**Comment by ShashankArora92** [comment]
Hey, I am facing the same issue after this update. I tried everything but nothing worked. All I came up with is, use command "sudo rfkill unblock all" then you can turn on your Bluetooth by using command "sudo systemctl restart bluetooth".
this will turn on your Bluetooth but the button is still not working.

**Comment by Ldev007** [comment]
@ShashankArora92 I know let's see when will our cool devs be able to fix it

**Comment by ShashankArora92** [comment]
If you find something please let me know.

**Comment by yousseefs** [comment]
I'm using Lenovo S145 and I've same problem here

**Comment by navrudh** [comment]
Same issue on Lenovo Legion Y540

**Comment by pramod21kadam** [comment]
I am facing same issue with Lenovo Ideapad 330

**Comment by SoumyaRanjanNaik** [comment]
Same issue with Acer Nitro 5 AN515-52 using Intel 9560 card and Dell Latitude 3410 using Qualcomm Atheros QCA6174 card.

**Comment by ju5tevg3niy** [comment]
Same issue with HP ProBook 430 G4

**Comment by achri97** [comment]
Hi , I am facing the same problem with Lenovo Thinkpad E14 Gen 2 using 11th Gen Intel i7-1165G7 . Also even if i use 'sudo systemctl restart bluetooth.service' bluetooth keeps disconnecting after a while.

**Comment by achri97** [comment]
Hi again , so after a lot of digging i found that the problem is BlueZ 5.55 as mentioned [here](https://bugs.mageia.org/show_bug.cgi?how%20to%20remove%20updates%20in%20ubuntuid=27314) so the problem is solved in newer versions 5.56-5.58

**Comment by leviport** [comment]
I updated that link, as per: https://github.com/pop-os/pop/issues/1668#issuecomment-826374292

Thanks for the info!

**Comment by TomorrowStrange** [comment]
> Hi again , so after a lot of digging i found that the problem is BlueZ 5.55 as mentioned [here](https://bugs.mageia.org/show_bug.cgi?id=27314) so the problem is solved in newer versions 5.56-5.58

Hi, I'm also having the same problem, how could I update the BlueZ package on Pop! _OS 20.10 properly? I checked the repositories and realized that only versions 5.55ubuntu1 and 5.55ubuntu1.1 are available. Is there a repository that I can add that has the new versions? Or do I have to compile it from source?

**Comment by ShashankArora92** [comment]
Hello,
System76 has given bluez version update "Version: 5.53-0ubuntu3.1", Bluetooth is working better than before still its button in Pop os is not working properly.

**Comment by bumjrah** [comment]
If it makes anyone feel better, as of time of making this comment. Bug still exists even on **Arch** with Bluez 5.58-1, only a restart of the service brings bluetooth back to life

**Comment by Ldev007** [comment]
### ALRIGHT GUYS ! I HOPE THAT I HAVE FOUND **A SOLUTION** FOR US !

Here we go.

Execute following commands as written below :

- sudo hciconfig hci0 down
- sudo rmmod btusb
- sudo modprobe btusb
- sudo hciconfig hci0 up

Idk how this magic happened eventually on next reboots the bluetooth started working ! It might take you to click the on and off buttons few times (3-4) but it will work without a need of separate workout to be done on each reboot !

Congrats everyone ! and thanks to this amazing person ! I'll drop his post's link too.

CREDIT GOES TO :

https://bbs.archlinux.org/viewtopic.php?id=171357

Peace out ! :crossed_fingers: :smile:

**Comment by lucasmarinb** [comment]
> ### ALRIGHT GUYS ! I HOPE THAT I HAVE FOUND **A SOLUTION** FOR US !
> Here we go.
> 
> Execute following commands as written below :
> 
> * sudo hciconfig hci0 down
> * sudo rmmod btusb
> * sudo modprobe btusb
> * sudo hciconfig hci0 up
> 
> Idk how this magic happened eventually on next reboots the bluetooth started working ! It might take you to click the on and off buttons few times (3-4) but it will work without a need of separate workout to be done on each reboot !
> 
> Congrats everyone ! and thanks to this amazing person ! I'll drop his post's link too.
> 
> CREDIT GOES TO :
> 
> https://bbs.archlinux.org/viewtopic.php?pid=1953936#p1953936
> 
> Peace out !

Worked for me, thanks for posting!

**Comment by rodrigorichter** [comment]
I have a desktop PC with an MPOW 5.1 dongle. I had this exact same problem. Finally I was able to fix. I follow the very last item from the system76 support page: https://support.system76.com/articles/bluetooth

I downloaded and installed the latest linux-firmware_1.199_all.deb linux firmware, shut down the PC and turned it on again(as opposed to restart) and it worked.

**Comment by ariedov** [comment]
> ### ALRIGHT GUYS ! I HOPE THAT I HAVE FOUND **A SOLUTION** FOR US !
> 
> Here we go.
> 
> Execute following commands as written below :
> 
>     * sudo hciconfig hci0 down
> 
>     * sudo rmmod btusb
> 
>     * sudo modprobe btusb
> 
>     * sudo hciconfig hci0 up
> 
> 
> Idk how this magic happened eventually on next reboots the bluetooth started working ! It might take you to click the on and off buttons few times (3-4) but it will work without a need of separate workout to be done on each reboot !
> 
> Congrats everyone ! and thanks to this amazing person ! I'll drop his post's link too.
> 
> CREDIT GOES TO :
> 
> https://bbs.archlinux.org/viewtopic.php?pid=1953936#p1953936
> 
> Peace out ! crossed_fingers smile

It works for me, but after a complete shutdown-boot cycle I have the same issue again.

**Comment by SaiSandeepKantareddy** [comment]
Can we write any automated loop for these commands to work every time?
