### ISSUE TITLE
External display not working anymore via USB-c dock after updating to kernel 5.11

### ISSUE THREAD

**Issue by systemverwalter** [pop-os/pop#1641]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I usually connect a USB-c dock to my laptop.
An external monitor is connected to the USB-c dock by DP.
It used to work fine with kernel 5.8 and DKMS evdi driver 1.7.0 (displaylink-driver-5.3.1.34 installed).
With the update to kernel 5.11, the evdi driver 1.7.0 won't install anymore.
After some fiddling, the installation of the 1.9.1 version went OK (displaylink-driver-5.4.0-55.153).
The monitor is now recognized in the display settings but it won't show any content. The screen stays black.

**Steps to reproduce (if you know):**
Update to kernel 5.11 and install displaylink-driver-5.4.0-55.153 (https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu)
Try to get a DisplayPort connected screen working.

**Expected behavior:**
External display should work out of the box as with kernel 5.8.

**Other Notes:**

**Comment by chrros95** [comment]
With latest Displaylink-Driver (v5.4.0 - Apr 6, 2021) the issues should be resolved - it works on my system.

BTW. The root cause was evdi in my case.

**Comment by PaulVanSchayck** [comment]
This also happens to me. But also on non-displaylink USB-c video. I've uninstalled the displaylink drivers to be sure those are not the cause.

**Comment by ksmithut** [comment]
I mentioned this on another issue, but I'm also having issues connecting to my external monitor, but rather than just not working, it locks up my entire system (System76 oryp5). I've tried updating the latest Displaylink-Driver but it doesn't resolve it.
