### ISSUE TITLE
Desktop Icons NG(DING) make gnome unresponsive after lock and unlock

### ISSUE THREAD

**Issue by sazconaitbit** [pop-os/pop#1766]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Desktop-Icons-NG (DING) gnome extension

**Issue/Bug Description:**

gnome shell apps unresponsive after lock and unlock, the shell menu, dock, etc. is usable but apps and windows open before the lock and unlock become unresponsive also you can not open new apps.

I found that this is caused by the extension: Desktop Icons NG (DING) disabling this extension fix the issue. I put this here because this extensions comes by default with pop os

This is not cause by Nvidia or any graphic mode, I test it with and without Nvidia same result.

Just disable the extension fix the problem

**Steps to reproduce (if you know):**
just lock then unlock, not needed to suspend the PC to have the issue.

**Expected behavior:**
Lock and unlock works perfectly without make gnome unresponsive having the default pop os extensions enabled

**Comment by wellington1993** [comment]
I have similar problem when return from other Linux TTYs. 

After I've got to CTRL+F5 or CTRL+F6 or CTRL+F7.
And return to the gnome-shell, I can't click or manipulate the interface.

**Comment by bflanagin** [comment]
Are you using Xorg or Wayland @sazconaitbit  I'm not seeing the issue on my end but I might not have everything exactly as you do. Also have you run updates to make sure you're on the latest version of gnome-shell and Cosmic?

**Comment by Figureix** [comment]
I'm wondering if this could be related to this?
https://gitlab.com/rastersoft/desktop-icons-ng/-/issues/162

My syslog is full of entries from Desktop Icon NG gnome extension throwing exceptions.

**Comment by jacobgkau** [comment]
> I'm wondering if this could be related to this?
> https://gitlab.com/rastersoft/desktop-icons-ng/-/issues/162

That should already have been fixed with https://github.com/pop-os/desktop-icons-ng/pull/14. Please install all updates and run `apt policy gnome-shell-extension-desktop-icons-ng`, the version number should end with `9b6cced`.

**Comment by l4sh** [comment]
Still ocurring for me. Commenting to remember to come back later on.

os-release:
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

Haven't checked with extensions disabled.

**Comment by l4sh** [comment]
Update:

I noticed that it can occur after returning from suspend or lock screen. Also upon locking/suspending a few times it can return to normal.

Tried with extensions enabled and disabled. Issue persists.

Also behavior is not consistent. Sometimes it stops working and other times it just works normally after suspending.

Behavior is also inconsistent on what stops working. I've gotten:
- Left click does not work. This seems to be the prevalent one, happens every time.
- Right click does not work
- Windows key does not work
- Some combinations like Alt+F2 do not work
- All of the above

Checking with `xev` I noticed that the keys are detected but mouse inputs aren't. So this likely is occurring at a lower level than desktop.

Checked the Xorg log and though this could be part of the issue. Not sure.

```
[396632.770] (II) event8  - Corsair CORSAIR M65 RGB ELITE Gaming Mouse: Enabling spurious button debouncing, see https://wayland.freedesktop.org/libinput/doc/1.20.0/button-debouncing.html for details
[542872.564] (EE) client bug: timer event21 debounce: scheduled expiry is in the past (-3175ms), your system is too slow
[542872.564] (EE) client bug: timer event21 debounce short: scheduled expiry is in the past (-3188ms), your system is too slow
[542872.564] (EE) client bug: timer event21 debounce: scheduled expiry is in the past (-3175ms), your system is too slow
[542872.564] (EE) client bug: timer event21 debounce short: scheduled expiry is in the past (-3188ms), your system is too slow
```

Tried unplugging and reconnecting the mouse a few times and nothing changed.

Tried reapplying udev rules and it went back to normal. (`udevadm trigger` should be the only needed command)

```
sudo udevadm control --reload-rules
sudo udevadm trigger
```

I'm thinking this is specific to some hardware setups.

For context
- PC: System76 Darter Pro 11
- Keyboard: Keychron C3 pro
- Mouse: Corsair CORSAIR M65 RGB ELITE
- Keyboard and mouse are usually connected to a Wavlink USB dock
