### ISSUE TITLE
Cannot reboot or shutdown. Stuck on 

### ISSUE THREAD

**Issue by chrismcolvin** [pop-os/pop#2389]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Unknown

**Issue/Bug Description:**
Cannot reboot or shutdown my PC without running into and getting stuck on this message:
`systemd-shutdown[1]: Waiting for process: systemd-udevd, systemd-udevd`

After this I must hard-shutdown the PC by holding the power button. Checked dmesg after booting back up and am encountering a few errors:

`[    0.085191] x86/cpu: VMX (outside TXT) disabled by BIOS`
`[    4.797330] hdaudio hdaudioC0D2: Unable to configure, disabling`
`[    6.194677] mt76x2u 1-10.2:1.0: could not get hardware semaphore for ROM PATCH`
`[   13.329615] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to grab modeset ownership`

I did try leaving it overnight to see if it was just taking a long time, but it was still stuck the next morning.

**Steps to reproduce (if you know):**
Just shutting down or rebooting, whether by GUI or from terminal.

**Expected behavior:**
Shutdown or reboot without getting stuck.

**Other Notes:**
I believe I've read something about the Nvidia error being related to the latest drivers, but I'm honestly pretty lost as to what's causing the hangup on shutdown. Any help is appreciated!

**Comment by Seibz** [comment]
We recently pushed out the 5.17.5 release of the Linux kernel. I believe what you're experiencing is related to the System76 NVIDIA driver being a bit surprised by this latest kernel. This should be corrected by reinstalling the System76 NVIDIA driver. To do so, please open the Terminal application (which you can find in the Launcher or Applications view in the top left), then enter the following commands:
```

sudo apt update
sudo apt purge ~nnvidia
sudo apt clean
sudo apt update -m 
sudo dpkg --configure -a
sudo apt install system76-driver-nvidia
```

After that, if you reboot, are you able to switch graphics modes again? Please let me know what you find, or if you have any questions. Thank you!

**Comment by jacobgkau** [comment]
Reinstalling the NVIDIA driver is a good troubleshooting step to take, but the `Failed to grab modeset ownership` dmesg entry is normal and does not indicate a problem. The driver should not be "surprised" by kernel updates.

**Comment by chrismcolvin** [comment]
Tried reinstalling the Nvidia driver which resulted in no change, sadly.

**Comment by chrismcolvin** [comment]
Tried reinstalling Pop from scratch today. Still getting the same message:
`systemd-shutdown[1]: Waiting for process: systemd-udevd, systemd-udevd`

I also tried changing DefaultTimeoutStopSec time to 5s after reading this article: https://itsfoss.com/long-shutdown-linux/, but this didn't seem to change anything.

**Comment by chrismcolvin** [comment]
I'm starting to wonder if this issue could be the result of a BIOS setting? I don't remember changing anything, but last night I tried:
* Clean installing Pop on two different drives
* Clean installing Zorin OS
* Clean installing Ubuntu
They all resulted in the same issue. 

However, I did in one instance see a message come up that said something like ```      Tainted: P       OE    5.17.5...```

**Comment by Seibz** [comment]
What hardware is this?

**Comment by chrismcolvin** [comment]
@Seibz tried using hwinfo but didn't seem to work. Here's what I know off-hand:
Mobo: ASUS Prime B560M-A
CPU: i5 12600k
GPU: RTX 3060
16GB RAM
HP 512GP NVMe Drive (main)
PNY 240GB Sata SSD
WD Blue 2TB HDD

**Comment by chrismcolvin** [comment]
Since I have not, so far, been able to find a solution, I guess my next question would be: is having to hard-power off my PC going to hurt it over time? Assuming I wait until Linux gets hung up on whatever it's hung up on? I suppose I can live with that so long as I'm not damaging the system.

**Comment by chrismcolvin** [comment]
Well, good news and bad news. Good news is my PC started shutting down and rebooting without having to hold the power button. Bad news is that I didn't actually change anything, so I don't know what made it start working.
