### ISSUE TITLE
Boot freezes on: A start job is running for dev-mapper-cryptswap

### ISSUE THREAD

**Issue by spysiuk** [pop-os/pop#316]
**Distribution:**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description:**
After recent update boot freezes on A start job is running for dev-mapper-cryptswap ... / no limit.
Until I press any key timer is increasing.

**Expected behavior:**
Boot without user intervention.

**Other Notes:**
I tried to comment swap in /etc/fstab and /etc/crypttab but after that I didn't get login screen - had to go to other terminal, remove comments in both files and reboot machine.

**Comment by mmstick** [comment]
You'd only need to comment the crypttab, and you would need to always do an `update-initramfs -u` after that.

**Comment by mmstick** [comment]
What's the contents of your fstab / crypttab?

**Comment by spysiuk** [comment]
fstab:
UUID=2A29-825C  /boot/efi  vfat  umask=0077  0  0
UUID=24dddfd8-0034-4eb8-ba71-4c3aa3ff83fb  /  ext4  noatime,errors=remount-ro  0  0
UUID=d7636828-6d7f-4088-a1f9-93fa43c85052  /home  ext4  noatime,errors=remount-ro  0  0
/dev/mapper/cryptswap_qSCcI  none  swap  defaults  0  0

crypttab (currently commented):
# cryptswap_qSCcI UUID=ecb21db5-ce2a-4668-864c-ca43b75422f8 /dev/urandom swap,offset=1024,cipher=aes-xts-plain64,size=512

**Comment by mmstick** [comment]
Should remove the /dev/mapper part from the fstab, too.

**Comment by zvirdaniel** [comment]
I have exactly the same issue as well. `systemd-analyze blame` told me that `systemd-cryptsetup@cryptswap.service` took over 50 seconds to load. I guess that is when I pressed some buttons.

**Comment by zvirdaniel** [comment]
After commenting out `cryptswap UUID=ca2f2392-903f-4731-b24f-0e5aaf30803a /dev/urandom swap,offset=1024,cipher=aes-xts-plain64,size=512` from `/etc/crypttab` and `/dev/mapper/cryptswap none swap defaults 0 0` from `/etc/fstab` I was left without an active swap partition and the system booted after several reboots. `systemd-analyze blame` told me that `plymouth-quit-wait.service` took 2min 11.275s to boot. Possible solutions?

**Comment by rkennesson** [comment]
ran into this when installing with WMware and VirtualBox even when choosing not to encrypt the drive. Is there a fix available and referably one I can use during install. I tried some of the others maybe I typed them in wrong or didn't follow them properly but I couldn't get them to work.

specifically I get this error

> A start job is running for /dev/mapper/cryptswap (_min _s / no limit)

**Comment by mmstick** [comment]
Sounds like you've deleted the swap partition, or reformatted it after the installer created it. The swap partition created by the installer will always be encrypted, but it expects the swap partition to have the same UUID between boots so that it may create an encrypted swap partition inside of the swap partition.

**Comment by rkennesson** [comment]
I haven't done anything other than a fresh install in a VM using the popOS installer and reboot.

**Comment by rkennesson** [comment]
Here is the full install log

https://pastebin.com/hgFPbaVs

**Comment by mmstick** [comment]
```
cryptswap UUID=7e82b0cf-15e0-4241-9d0b-08364d846701
```

If you wait long enough, systemd will give up trying to load the cryptswap entry. Could you confirm that the UUID of the swap partition is the same as in the crypttab file?

**Comment by rkennesson** [comment]
crypttab:
```
cryptswap UUID=7e82b0cf-15e0-4241-9d0b-08364d846701 /dev/urandom swap,offset=1024,cipher=aes-xts-plain64,size=512
```

`cryptswap UUID=7e82b0cf-15e0-4241-9d0b-08364d846701` It looks the same to me.

**Comment by mmstick** [comment]
Strange. A copy of your system logs would be helpful. This command would dump the logs collected since the last system boot, to the `system.log` file in your home folder (if you aren't logged in as root).

```
journalctl -b0 > ~/system.log
```

**Comment by rkennesson** [comment]
I haven't been able to boot into the system and can only access the install ISO.

To switch to single user mode i've added a `1` and `single` (as some sites suggest) to the grub menu item and the system still hangs with ( _ / no limit).

**Comment by mmstick** [comment]
What VM are you using?

**Comment by rkennesson** [comment]
I'm using VMware. My first troubleshooting step was to try it in VirtualBox but I had the same issue. I'm checking it in VirtualBox again right now just to make sure.

**Comment by mmstick** [comment]
I've only been testing installs in KVM/QEMU VMs from a Pop!_OS host. I'll have to try this out in those two.

**Comment by Seppukucide** [comment]
I am hitting the same issue.  VMplayer trying to install 19.04 using the amd/intel image.

**Comment by rkennesson** [comment]
Are you on the latest VMplayer and/or on Windows 10? My issue was with the latest VMWare Workstation or latest VirtualBox and Windows 10.

**Comment by Seppukucide** [comment]
I'm on VMWare 14, I havent updated to 15 yet.  I am on the latest Win10.

**Comment by Spoil001** [comment]
I'm hitting the same issue without using a VM.
UIDs match 
```
/etc/fstab 
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system>  <mount point>  <type>  <options>  <dump>  <pass>
PARTUUID=e4086903-5e38-4f57-beca-e06a05223493  /boot/efi  vfat  umask=0077  0  0
/dev/mapper/cryptswap  none  swap  defaults  0  0
UUID=27108123-06bd-4347-a0c5-9ea2ba62a034  /  ext4  noatime,errors=remount-ro  0  0
```
```
/etc/crypttab 
cryptswap UUID=f8e00ba8-e6b6-446a-a37a-1acfcfafc679 /dev/urandom swap,offset=1024,cipher=aes-xts-plain64,size=512
```

```
ls -Al /dev/disk/by-uuid 
insgesamt 0
lrwxrwxrwx 1 root root 10 Apr 24 18:46 26E000B4E0008BED -> ../../sda1
lrwxrwxrwx 1 root root 10 Apr 24 18:46 27108123-06bd-4347-a0c5-9ea2ba62a034 -> ../../sdb3
lrwxrwxrwx 1 root root 10 Apr 24 18:46 35E7-8D4F -> ../../sdb1
lrwxrwxrwx 1 root root 10 Apr 24 18:46 4378585b-b624-4132-a9da-0d7898ddbb9a -> ../../dm-0
lrwxrwxrwx 1 root root 10 Apr 24 18:46 C00A06010A05F566 -> ../../sda4
lrwxrwxrwx 1 root root 10 Apr 24 18:46 CE01-1FAA -> ../../sda2
lrwxrwxrwx 1 root root 10 Apr 24 18:46 f8e00ba8-e6b6-446a-a37a-1acfcfafc679 -> ../../sdb2
```

**Comment by Gabriel-p** [comment]
Same issue here. Freshly installed Pop-OS 19.04 on an empty SSD disk. 4 min and counting waiting for cryptswap (first boot after installing the OS with no encryption)

**Comment by mmstick** [comment]
There seems to be a correlation with vmware and virtualbox. I do multiple installs a day with KVM/QEMU without issue. I wonder, are these EFI or legacy BIOS installs? I'm always using the OVMF firmware.

**Comment by Gabriel-p** [comment]
In my case I'm installing on an old Dell laptop through a burned USB. Not sure if this is a "legacy BIOS install"?

Also I checked installing with the encrypted disk, and I get same issue: waiting for cryptswap, no limit.

**Comment by rkennesson** [comment]
On VirtualBox I switched to EFI mode (using the standard install and ejecting the virtual disk) and I get this error at startup

    Boot Failed. EFI DVD/CDROM

after a string of reboots where sometimes it boots and sometimes it doesn't it now seems to boot reliably but shows that same error everytime.

**Comment by TylerSchmidtke** [comment]
I just experienced this as well on an 19.04 installation on a SSD, no virtualization.

**Comment by rkennesson** [comment]
Thank you all for posting.

If you know of anyone else having issues ask them to post their experience and if they have any solutions.

**Comment by Spoil001** [comment]
My short term solution was to remove the cryptswap.
Losely based on this article: https://www.logilab.org/blogentry/29155
First remove the cryptswap, then edit /etc/crypttab (comment the cryptswap line) and etc/fstab change the cryptswap line to normal swap.
Reboot

**Comment by nekdolan** [comment]
I have the same issue with a clear 19.04 install (+some cloud services) on a lenovo l460. I had no issue with 18.04. If I restart after the system hangs things seem to work fine. I also don't seem to be able to shut down the system.

**Comment by pierrep** [comment]
I just did a fresh install of pop-os 19.04 on a Dell XPS 13 9360, got the latest updates, then shutdown. On restart just now, I'm getting this error.

**Comment by flucoe** [comment]
I just did a fresh install too (pop-os 19.04), got the latest updates, and have the same problem. Rebooting didn't change things.

**Comment by mmstick** [comment]
If you add `nofail` as a mount option in `/etc/fstab` for the `cryptswap` entry, does this allow you to boot? That would at least allow you to continue booting even if the swap partition cannot be found. Though it would be nice to know what's causing your swap partition to disappear.

**Comment by flucoe** [comment]
Sorry, I just saw this. Today, without having made any changes, I didn't have any issues. I can try your suggestion but I wouldn't know how to identify whether adding `nofail` makes a difference.

**Comment by mmstick** [comment]
If you're able to boot, it's working.

**Comment by pierrep** [comment]
I'm getting this most of the time now, whenever I do a cold boot.
My fstab looks like this:
`# <file system>  <mount point>  <type>  <options>  <dump>  <pass>
PARTUUID=e80261e0-2ee4-4c33-b93c-0f8dcd263b7c  /boot/efi  vfat  umask=0077  0  0
PARTUUID=e6d29290-76bb-43f2-931d-f5bc87307013  /recovery  vfat  umask=0077  0  0
UUID=09c20a5d-6415-48a5-9a9c-f05323cba3e4  /  ext4  noatime,errors=remount-ro  0  0
/dev/mapper/cryptswap  none  swap  defaults  0  0
`
Any thing I can do to stop this? I did a vanilla install with no custom partitioning.

**Comment by Nodocify** [comment]
I also experienced this same issue with a fresh install of 19.04 on my galago pro, default options through the installer. The problem occured at first reboot after install. Then I reinstalled and this time it was after a couple reboots that I encountered the `A start job is running for /dev/mapper/cryptswap`. I also opened a support case with System76, but they had no idea how to assist. They weren't even aware this github issue existed. 

So this is my solution as I feel that a cryptswap is overkill and I understand the security concerns with NOT having swap encrypted. I took the idea from @Spoil001 where he mentioned to disable the cryptswap.

Do this at your own risk and please understand what you are doing before doing it. (Obviously replace the device names with the ones from your setup).

## Boot any linux live cd

Unlock luks
`sudo cryptsetup luksOpen /dev/nvme0n1p3 cryptroot`
enter password

Get the logical volume to mount.
`sudo lvscan`

Mount the logical volume.
`sudo mount /dev/data/root /mnt`
`cd /mnt/etc`

`sudo vim fstab`
comment out the swap line

`sudo vim crypttab`
remove the cryptswap line

`reboot`
This allowed Pop_OS to boot without a swap.

## Pop_OS
Next disable the cryptswap and create a standard swap.

Turn off swap.
`sudo swapoff -a`

Format a normal swap over the cryptswap.
`sudo mkswap /dev/nvme0n1p4`

Turn on swap.
`sudo swapon /dev/nvme0n1p4`

Add entry to fstab for future reboots.
`sudo vim /etc/fstab`
Uncomment and replace /dev/mapper/cryptswap with /dev/nvme0n1p4
Reboot and make sure that you now have a standard swap mounted.

I needed to get this resolved quickly and get my computer up and going for work. Hopefully this can help someone as a quick and dirty solution.

@mmstick I tried your `nofail` solution of adding that to the swap options in `/etc/fstab`. It didn't prevent the error message and I let it go for 10 minutes in which it didn't timeout. I then shutdown and did the above. Please let me know if there is any assistance I can offer to better assist in an official resolution.

**Comment by mmstick** [comment]
@Nodocify You can try adding `nofail` to the crypttab entry's options, too.

**Comment by pierrep** [comment]
Just wondering - should the swap be encrypted even if encryption was turned off in the installer, as it was in my install (I chose no encryption)?

**Comment by mmstick** [comment]
Swap is always encrypted

**Comment by shaunhey** [comment]
Just wanted to leave a comment that I’m also seeing this occasionally on 19.04 installed directly on a Dell Latitude 7370 (XPS’ cousin). I’ve since disabled cryptswap as others recommended and so far I have not encountered the issue again.

**Comment by earlev4** [comment]
Hello. 
I am experiencing the same issue on VirtualBox (Version 6.0.6 r130049 (Qt5.9.5)) and VMware Workstation 15 Pro (Version 15.0.4 build-12990004). 
Boot up just sits at:
**A start job is running for /dev/mapper/cryptswap**
I just installed RHEL 8 in VirtualBox and did not experience any issues. Also tried booting up in GRUB with "Ubuntu, with Linux 5.0.0-13-generic (recovery mode)" and experienced the same issue.
Thanks!

**Comment by Draconicrose** [comment]
Also encountering this issue on Pop!_OS 19.04, installed on bare metal.

**Comment by pt8o** [comment]
Same here across two devices. My work device was on 18.10 and I upgraded to 19.04. My home computer was a wipe and clean install. It happens about 50% of the time. 

I did the `nofail` thing, so they will log in now if cryptswap is hanging, but after a 90 second timeout. Would love to get this resolved! Let me know if there's a log I can post or anything like that.

**Comment by luispjoaquim** [comment]
I can confirm this issue in two different laptops (bare metal install).

**Comment by YggrYergen** [comment]
I also confirm this issue on a lenovo.
(model name: 80UL; Pop!_os 19.04)


It gets "solved" as follows:

When initializing computer hit "fn+f2",
System will prompt to choose beetwen options to boot-in. 
Choose "pop!_os recovery".

System will load as a for-install version, do nothing but set the system to restart normally. This is, from the top-right menu.



Please comment if this method works for you. I'll come back with consistency report.

**Comment by reidstidolph** [comment]
Nothing substantial for me to add, other than "me too".

- Pop 19.04, Freshly installed and updated
- Lenovo X1 Carbon 5th gen
- Disk encryption enabled
- System had hung on shutdown, so I forced it off by holding down the power button.
- Hung on boot up exactly as described above.
- After 4 boot attempts, it booted fine.
- Subsequent reboots have gone normally so far (knock on wood).

**Comment by TrendMend** [comment]
Still no fix... I am stuck with 1min 30second wait time after adding nofail... but it would be nice to not have this issue at all, I really hope this gets elevated.

**Comment by mmstick** [comment]
@TrendMend We haven't able to replicate the issue (despite doing dozens of installs per day in the lab), so there's no way to determine the cause.

**Comment by mambojuice** [comment]
Same issue here. Just did a fresh install, HP EliteBook 1040. Installed updates after first boot, now second boot hangs at "A start job is waiting for /dev/mapper/cryptswap" for 5+ minute before I hard reboot. After enough restarts it eventually boots.

**Comment by lars-str** [comment]
Same bug for me. ASUS TP200S. Fresh install of version 19.04 and during first boot after installation the bug comes up... After several tries booting up the machine, the computer booted. But it seems that the bug is coming back randomly.. I've added now the `nofail` option, so there is now a limit of 1m30s..

**Comment by TeamLinux01** [comment]
I also ran into this problem on my Galago Pro (galp2).
I did a fresh install of Pop!_OS 19.04 intel/AMD v5 from a Samsung USB 3.0 flash drive.
Then I ran some custom setup scripts from my github repo, https://github.com/TeamLinux01/scripts pop_os_setup.sh
I also use an external WD 4TB USB 3.0 HDD, which is formatted Ext4.

**Comment by tobico** [comment]
I too am having this issue with a fresh install of Pop!_OS 19.04 running under Parallels on Mac. I did not enable encryption during install.

**Comment by konadave** [comment]
I've been experiencing this intermittently today. Fresh install of Pop!_OS 19.04 on a System76 Gazelle (gaze-12) on Monday. First saw the problem today, and have no idea what the issue is.

What I did find though that some might find helpful, is hitting Ctrl+Alt+Del caused it to bypass/skip the start job and it seemed to boot normally.

**Comment by SunnyYSSC** [comment]
I'm having the same issue on VM. I can boot into 18.10 and 18.04 just fine expect of 19.04. It will boot sometimes after restarting the VM several times. I also didn't enable encryption when installing. The suggestion from @konadave  does not work for me, maybe it is because I'm running on VM...

**Comment by darknmy** [comment]
> @TrendMend We haven't able to replicate the issue (despite doing dozens of installs per day in the lab), so there's no way to determine the cause.

I can add "mee too" to this thread. 
Acer Nitro 5 with M.2 SSD Intel Fresh Pop!_os 19.04 updated or not.
I see a message "a start job is running for cryptswap" every time I turn on and it will be off each time I press ctrl+alt+del.

**Comment by kiksen1987** [comment]
I'll add a "mee too" :) Fresh install on virtual box.

**Comment by wshaddix** [comment]
Same issue for me as well on a fresh bare metal laptop install. I hit "CTRL+ALT+DEL" as many times as it takes (usually no more than 3) to get it to boot. The message that it's hung up on is "A start job is running for /dev/mapper/cryptswap"

**Comment by dubl3a** [comment]
I was forced to boot into recovery mode and comment out the cryptswap entry in both fstab and crypttab respectively.  This allows me to boot without issue.  

As I have 32GB of ram, do not utilize sleep functions, do I need cryptswap at all?  Is this the proper way to disable it or should I do more?

**Comment by mmstick** [comment]
You're free to remove swap if you want, or disable encryption. However, note that disabling swap encryption would allow a malicious actor to read any sensitive content that was written to the swap partition.

**Comment by autonomousit** [comment]
@mmstick - Just had this happen while setting up a brand new Darter Pro with Pop OS 19.04 when it reboot after the initial encryption. 

CTRL+ALT+DEL allowed it to boot but before that it was hung indefinitely. The setup process continued and reboots after completing the user creation process where fine.

A few minutes later after installing some updates to Pop OS I rebooted (as requested by the update) and it occurred again. Since then both reboots and cold boots after a shutdown have been fine.

Let me know what info you want as there seems to be multiple attempts/ideas in this thread and it's unclear which are/aren't helpful

**Comment by raphaelcasimir** [comment]
Fresh install and upgrade gets me the same issue on first reboot...
Pop os 19.04 kernel 5.0.0-15
4.3 GB swap, 16GB ram, Intel 7300u, nvme ssd
Lenovo x270
This is really bad, I would like a stable OS... I hoped this OS could be used on a large computer park...
If you need any info to fix this do not hesitate to contact me.

**Comment by JPaveg** [comment]
Same here, PopOS 19.04, fresh install on a laptop.

Distribution: Pop!OS 19.04

Issue/Bug Description:
Frequent issues with shutting down & booting, hangs until I get sick of waiting and force the shutdown. Booting is chance - sometimes it hangs, sometimes it doesn't.

Shutdown hanging is not a result of user error - ie I don't have programs preventing the shutdown or user processes causing the hanging. This is on a fresh install. 

Expected behavior:
Boot & shutdown without user intervention.

Other Notes:
Upon hitting ESC while waiting to boot, I noticed the line the OP reported: "A start job is running for /dev/mapper/cryptswap (time here / no limit)

A response or suggestions would be appreciated.

**Comment by advaithm** [comment]
hey i am facing similar problem on a system install. it is a minor in convince 
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.04
Release:	19.04
Code name:	disco
attached is my log file
[system.log](https://github.com/pop-os/pop/files/3365841/system.log)

**Comment by sedmicha** [comment]
Same issue with a fresh Install of Pop OS 19.04 on my Acer Aspire 5, UEFI was used and no disk encryption. Reboots seem fine.

**Comment by advaithm** [comment]
same here UEFI mode, maybe it has something to with the use of UEFI? 
here is the output of systemd-analyze critical-chain
The time after the unit is active or started is printed after the "@" character.
The time the unit takes to start is printed after the "+" character.

graphical.target @1min 56.115s
└─multi-user.target @1min 56.115s
  └─hddtemp.service @1min 41.273s +125ms
    └─network-online.target @1min 41.272s
      └─NetworkManager-wait-online.service @1min 37.213s +4.058s
        └─NetworkManager.service @1min 33.085s +4.126s
          └─dbus.service @1min 32.778s
            └─basic.target @1min 32.775s
              └─sockets.target @1min 32.775s
                └─snapd.socket @1min 32.562s +212ms
                  └─sysinit.target @1min 32.473s
                    └─systemd-timesyncd.service @1min 32.130s +343ms
                      └─systemd-tmpfiles-setup.service @1min 31.449s +615ms
                        └─local-fs.target @1min 31.444s
                          └─run-user-120.mount @1min 39.474s
                            └─local-fs-pre.target @1min 31.320s
                              └─lvm2-monitor.service @1min 31.309s +10ms
                                └─lvm2-lvmetad.socket @1.296s
                                  └─system.slice @1.261s
                                    └─-.slice @1.261s

**Comment by 4SeasonsFlow** [comment]
I have just experienced this problem twice on fresh install of PopOS (boot remained at /dev/mapper/cryptswap for over 30 min first time, thought I did something wrong) on a Asus Vivobook e203na with celeron n3350, 4gb ram. After 1 or 2 reboots with ctrl alt del the system boots up and works fine. If I try another fresh install will it go away or do I just have to deal with it. BTW complete noob to Linux.

**Comment by advaithm** [comment]
4SeasonsFlow are you running pop os in UEFI mode?

**Comment by 4SeasonsFlow** [comment]
> 4SeasonsFlow are you running pop os in UEFI mode?

I think so but am not sure so I'll show you how I tried to check. I followed the 2nd Method of [this link](https://unix.stackexchange.com/questions/148356/how-to-know-if-im-booting-using-uefi) and below is what the terminal said.  The Kingston drive is what i used to try and then install pop os while the sandisk was just there for files. Also, the problem has not reappeared since the situation I mentioned in my previous post.

~$ sudo efibootmgr
BootCurrent: 0004
Timeout: 1 seconds
BootOrder: 0004,0005,0003,0006,0007,0001,0002,0008
Boot0001* UEFI:CD/DVD Drive
Boot0002* UEFI:Removable Device
Boot0003* UEFI: SanDisk, Partition 1
Boot0004* Pop!_OS 19.04
Boot0005* UEFI OS
Boot0006* UEFI: KingstonDataTraveler 3.0PMAP, Partition 1
Boot0007* UEFI: KingstonDataTraveler 3.0PMAP, Partition 1
Boot0008* UEFI:Network Device

**Comment by kenklak** [comment]
I can add to the chorus. This happens creating VMs using the Intel/AMD 19.04 ISO in both Windows and Linux, using VMWare Workstation 15 and VirtualBox, and whether you use encryption or not. And the message doesn't timeout. It simple doesn't allow you to go any farther.

I do have Pop on bare metal with no issue. Great OS, especially for us nVidia card folks.

**Comment by 4SeasonsFlow** [comment]
Can someone help? Having trouble using nofail method. I booted in recovery and entered 
> /dev/mapper/cryptswap none swap nofail,x-systemd.device-timeout=60 0 0
into the terminal. I just get told that no such file or directory exists.

**Comment by kenklak** [comment]
> Can someone help? Having trouble using nofail method. I booted in recovery and entered
> 
> > /dev/mapper/cryptswap none swap nofail,x-systemd.device-timeout=60 0 0
> 
> into the terminal. I just get told that no such file or directory exists.

Sorry, this isn't a terminal command. If you have entered the options to get to the root terminal prompt, you need to edit the /etc/fstab file (e.g. vi /etc/fstab) and look for a line like the one above. Replace the 'default' parameter with the 'nofail,x-systemd.device-timeout=60' (no quotes - they are just there to help. Then, save the changes.

**Comment by 4SeasonsFlow** [comment]
> If you have entered the options to get to the root terminal prompt

How do I access these options? Is it settings, nautilus or somewhere else? Sorry for the trouble.

**Comment by zarino** [comment]
I had this same issue too, starting a few days ago.

Pop!_OS 19.04
i5-8400
RX Vega 56
1 TB M.3 SSD (unencrypted)
Gnome 3.32.2

Machine would just hang on a black screen at startup maybe 3 out of 4 times. Eventually I found out I could display the console during that blank startup screen, and saw the dreaded:

    [ * * *    ] A start job is running for /dev/mapper/cryptswap (51s / no limit)

I left it to run for 10 minutes, then found this github ticket, forced a restart, was lucky enough to get straight in, and updated my `/etc/fstab` as @kenklak suggested:

    /dev/mapper/cryptswap none swap nofail,x-systemd.device-timeout=60 0 0

I also took the opportunity to allow `Esc` to display the console during startup, by editing my `/etc/default/grub` file and then running `update-grub`:

    GRUB_CMDLINE_LINUX_DEFAULT="splash"

I’ve restarted about a dozen times since then, and I’ve only seen the `cryptswap` message once, for about 20 seconds. Not sure whether the `nofail,x-systemd.device-timeout=60` change is to thank for that, or whether it’s just luck.

**Comment by advaithm** [comment]
go to boot use boot override and select your hard drive to boot into options

**Comment by GiorgioAresu** [comment]
I'm still having this issue on my Lenovo T430, UEFI install with encryption. There is really no definitive solution?

**Comment by kenklak** [comment]
I don't know of any. Strange thing is that I was only having this problem on Pop_OS VMs and yesterday, I had it once on my Pop_OS host. Rebooted, and it didn't happen again (and I made the /etc/fstab change just in case). Pop_OS comments that they haven't seen this, but clearly many people are. Very strange error given the randomness of its occurance.

**Comment by mmstick** [comment]
@kenklak We've seen it happen once or twice in the last year on a laptop, but restarting fixed it and it could not be replicated again, so it is in the rare "Heisenbug" category. It does appear to be non-QEMU VMs that experience the issue the most. System76 hardware appears to be largely unaffected.

**Comment by kenklak** [comment]
I see. Good to know and thanks for introducing me to QEMU lol. I didn't know about it until now.

**Comment by ryan-fox** [comment]
This issue happens to me frequently.  I'm running Pop_OS on bare metal on System76 hardware.

* Manufacture: **System76**
* Model: **Galago Pro**
* Model #: **galp2**

I originally installed 18.10 (cosmic) before upgrading to 19.04 (disco) via the software update (not a fresh install).  I can't remember if I experienced this issue before the upgrade or not.  To be honest, I've been working around the issue for a long time.

I will see the following if I hit a key after successfully putting in my passphrase to unlock the drive:

    [ * * *    ] A start job is running for /dev/mapper/cryptswap (51s / no limit)

To get past the issue I have to reboot and get lucky.  Today it's taken a lot of retries to finally get past the issue.

In my BIOS security tab I could see that the secure boot was enabled:

![system76-bios-security](https://user-images.githubusercontent.com/47123255/61458029-b23abc80-a937-11e9-8d98-f6b019bf3c40.jpg)

Once I was able to access my machine, I was able to confirm that I'm booting with UEFI enabled:

    $ sudo efibootmgr
    [sudo] password for kiba: 
    BootCurrent: 0005
    Timeout: 1 seconds
    BootOrder: 0005,0002,0001,0006,0000
    Boot0000* ubuntu
    Boot0001* UEFI: IP4 Realtek PCIe GBE Family Controller
    Boot0002* UEFI: IP6 Realtek PCIe GBE Family Controller
    Boot0005* Pop!_OS 18.10
    Boot0006* UEFI OS
    $ df -h --local | grep /boot
    /dev/nvme0n1p1         498M  212M  286M  43% /boot/efi

**Comment by pkulak** [comment]
I'm getting this on a brand new Meerkat. Haven't don't anything but update and run the browser a couple times.

**Comment by jmfranks** [comment]
> We've seen it happen once or twice in the last year on a laptop, but restarting fixed it and it could not be replicated again, so it is in the rare "Heisenbug" category. System76 hardware appears to be largely unaffected.

I have two System 76 meerkats which exhibit this -- one rarely and a new one consistently. Usually booting from the boot menu (F10) works.  Also commenting out the swap line in /etc/fstab works reliably.  But I assume I have no swap.  How can I mount an unencrypted swap partition?  Can I  use the partition from /etc/crypttab?  Would it have to be reformatted?

**Comment by TrendMend** [comment]
I am constantly getting this error on my acer aspire laptop, I would be willing to ship it out to you guys/gals as long as I get it back sometime this year... It has an ssd so shipping (shouldn't) kill the install.

**Comment by horrokotoj** [comment]
Hi guys!
Thanks for some great posts!
The nofail comment in fstab seems to have resolved the issue for me. At least partly.
Now, when I try to boot I seem to be able to start and load the OS but no UI emerges.
Lines stating processes that start during boot stops at either [ OK ] Started LSB: automatic crash report generation, or at [ OK] started GNOME Display Manager.
Does any one have a clue what might have happened here?

**Comment by TomFaulkner** [comment]
I have rebooted a dozen times so far today and not been able to get passed this issue. Another user is in the same situation in the Pop subreddit.

I am on a Galago Pro on Pop 19.04. I have had this issue off and on for months but it has never taken this many attempts.

**Comment by rstrube** [comment]
This happens occasionally on my Darter Pro 2019.  I would estimate 1 time in every 20 boots.  It also sometimes happens when shutting the system down.

**Comment by jmfranks** [comment]
I can tell you what seems to have worked for me. YMMV.  I have two meerkats exhibiting this issue. On setup I chose unencrypted file systems. I have commented out the lines involving cryptswap in both /etc/fstab  and /etc/crypttab and made no other changes.  After that I have not seen any boot problems. Of course you have to boot once at least in order to make these changes.  What has surprised me is that there is still a mounted swap partition (as shown in /proc/swaps) despite no swap partition being listed in /etc/fstab.  I assume this swap is not encrypted, but that is what I expected when I chose an unencrypted file system.

**Comment by jackpot51** [comment]
@mmstick this looks like a systemd bug - https://github.com/systemd/systemd/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cryptography

**Comment by rstrube** [comment]
@jackpot51 @mmstick because this issue is affecting a large number of users, perhaps System76 could provide some official instructions on how to disable cryptgraphic swap? Simply commenting out the line in the fstab would completely disable swap no?

**Comment by rstrube** [comment]
@Nodocify 
Would this work:

```
sudo swapoff -a
sudo mkswap /dev/nvme0n1p4
sudo swapon /dev/nvme0n1p4
sudo vim /etc/fstab
```

Comment out current `/dev/mapper/cryptswap` line and replace with:

```
PARTUUID=f0c3ae89-9ef2-4c19-8a90-bf6439f5869f none swap defaults  0 0
```

Where UUID is the UUID of the partition

Also comment out the cryptswap line in `/etc/crypttab`

I noticed that you used the device label (e.g. `/dev/nvme0n1p4`) in the `/etc/fstab` file, but the rest of the file uses partition UUIDs.

**Comment by mmstick** [comment]
Of course, it needs to be the PARTUUID, which is different from the file system-specified UUID, fetched from `lsblk -o NAME,FSTYPE,PARTUUID`. Only MBR and GPT tables have PartUUIDs, and MBR emulates the support at best.

**Comment by mmstick** [comment]
I believe I've found a solution. I will need to figure out how it can be applied in an automatic fashion, however.

**Comment by mmstick** [comment]
Try this:

    sudo systemctl edit systemd-cryptsetup@cryptswap.service

Then paste and save

    [Service]
    ExecStartPost=/sbin/udevadm trigger /dev/mapper/%i

It should be fixed. It's a bug in cryptsetup's systemd integration.

**Comment by jmfranks** [comment]
@rstrube @mmstick 
_rstrube says: Simply commenting out the line in the fstab would completely disable swap no?_

I  think not necessarily.   From https://wiki.archlinux.org/index.php/Swap#Activation_by_systemd

> _systemd activates swap partitions based on two different mechanisms. Both are executables in /usr/lib/systemd/system-generators. The generators are run on start-up and create native systemd units for mounts. The first, systemd-fstab-generator, reads the fstab to generate units, including a unit for swap. The second, systemd-gpt-auto-generator inspects the root disk to generate units. It operates on GPT disks only, and can identify swap partitions by their type GUID, see systemd#GPT partition automounting for more information._

I am running two systems with no swap entry in /etc/fstab and nothing in /etc/crypttab.  Both seem to have swap activated on the swap partition.

**Comment by jmfranks** [comment]
Also from https://wiki.archlinux.org/index.php/Systemd#GPT_partition_automounting

**GPT partition automounting**

> On a GPT partitioned disk systemd-gpt-auto-generator(8) will mount partitions following the Discoverable Partitions Specification, thus they can be omitted from fstab.

**Comment by mmstick** [comment]
I've created a patch for systemd that seems to work. I will do some further testing before it's made available as an update.

**Comment by rstrube** [comment]
I just updated the systemd packages from the System76 proposed PPA, and now on a Darter Pro 2019, I was successfully able to boot 10/10 times.  Ordinarily I run into issues once every 10 times or so with the cryptswap problem.

The package versions that I updated to was **systemd 240-6ubuntu5.2pop1**

**Comment by rstrube** [comment]
I've performed another 15 boot sequences and have *not* run into the cryptswap issues.  This fix has been working very well for me.

**Comment by siistibuddy** [comment]
How are you guys able to implement these fixes when POP won't even boot passed the cryptswap step?
I have tried every keystroke imaginable.
Also @mmstick, VMWare has a ton more adoption than QEMU, would you be willing to add player to your QA testing?

**Comment by MarkJaroski** [comment]
Hi mmstick, are you going to do a pull request upstream for this bug?

I have this problem on Ubuntu 19.04 on a Dell Sputnik, so I think it's a little more widespread than Pop.

**Comment by kenklak** [comment]
> How are you guys able to implement these fixes when POP won't even boot passed the cryptswap step?
> I have tried every keystroke imaginable.
> Also @mmstick, VMWare has a ton more adoption than QEMU, would you be willing to add player to your QA testing?

I believe upon first start (after the boot prompt), I held down the Space bar and it gives you a menu where you can choose Pop_OS Recovery. When choosing that, I was fortunate that it gave me some options to choose to enter Root terminal mode. From there, I edited the /etc/fstab.

**Comment by mmstick** [comment]
@MarkJaroski I did, as you can see from the linked reference above your comment. They will not accept the patch upstream because it is a workaround, rather than fixing the root cause, which is currently unknown.

**Comment by mmstick** [comment]
The fix has been pushed to stable.

**Comment by rkennesson** [comment]
@siistibuddy I had the same issue with virtualbox but I was able to switch to UEFI mode in settings and get it to boot after a few reboots. I didn't use it very long so I don't know if the issue would have come back.

VMWare Player and Oracle VirtualBox (one or both) would be a great addition to the testing process given how many people use these programs.

I can't login for the first time because of this issue. I've tried holding space but I don't know if I'm not holding it at the right time. When I press the power button should I hold SPACE immediately after or after I press 'Ubuntu' on the grub menu and it starts to boot up. I've tried it both ways but maybe it's not properly set up for that yet because I don't have any users or anything set up because I haven't been able to get to the first boot user setup screen.

The only other option I can think of is to boot into a live CD and edit the configs from the live CD.

**Comment by mmstick** [comment]
We create new ISOs regularly, so the next ISO will have the fix out of the box.

**Comment by dubl3a** [comment]
> 
> 
> The fix has been pushed to stable.

I've applied that fix by using the Proposed PPA.  I initially had great success without getting the cryptswap infinite timeout error.  Now, every so often, I still get the timeout on cryptswap but at least there is a 1m30sec limit.  It's very random and would love to understand why it's faulting.

**Comment by mmstick** [comment]
systemd is waiting for a udev notification that the swap partition has been created, but it isn't receiving that notification after the `mkswap` command completes successfully. The fix in stable adds `udevadm trigger /dev/mapper/$cryptswap` to be run after `mkswap`, which should guarantee that systemd sees the notification.

**Comment by thebravoman** [comment]
This issue just broked a perfectly fine working Ubuntu 19.04. No new installation. No package. Has been working for month. Decide to restart to star fresh an spend my day on migrating to 19.10.

Now there is "A start job is running for /dev/mapper/cryptswap1 ( x min y sec/ no limit)

**Comment by JohannPopper** [comment]
It's happening again fyi. Perhaps the pop downstream systemd patch was accidentally not applied in the lastest upgrade?

**Comment by murkyness** [comment]
I have the same problem @mmstick 

Was this ever solved? Will it ever be solved? Is there a workaround?

**Comment by mmstick** [comment]
There will be an updated systemd package with the patch re-applied. Upstream believes they've fixed the issue, and although we can't replicate it on any of our systems, I've re-added the patch for those who are still having the issue.

**Comment by migumelar** [comment]
Im experiencing this issue out of sudden and force restart multiple times didn't work.

Do I have any options other than reinstall pop os? :(

**Comment by pflanzenandi** [comment]
I also have this problem after reformatted the swap partition.

**Comment by Novantric** [comment]
Got jumpscared with this whilst messing around with encrypting my swap, and now my laptop takes forever to boot...

**Comment by Ryuuusuke** [comment]
this still happens to me
