### ISSUE TITLE
6.16.3 Crash

### ISSUE THREAD

**Issue by luanlouzada** [pop-os/pop#3575]
[https://prnt.sc/H9AN-zbvPA50](url)
**System Information:**

  * **OS:** Ubuntu 24.04 with Cosmic Desktop Alpha DE
  * **Kernel (Problematic):** `6.16.3` (installed via System76/Pop\!\_OS dev repository)
  * **NVIDIA Driver:** `nvidia-driver-570-open`
  * **Driver Version:** `570.172.08-1pop1~1753974963~24.04~1f5276b`

**Issue Description:**
After running `sudo apt upgrade` with the System76/Pop\!\_OS development repository enabled, the system installed kernel `6.16.3` and updated several core components (`systemd`, `udev`, etc.) to Pop\!\_OS versions. After a reboot, the Cosmic Desktop session fails to start, leading to a black screen or being kicked back to the TTY. The logs indicate a fatal crash in `cosmic-comp` due to a GPU memory allocation failure (EGL `BAD_ALLOC`).

-----

### **Relevant Log Entries**

Here are the relevant log snippets showing the cascading failure, captured via `journalctl`.

**1. `cosmic-comp` (Graphics Compositor) Crash**

This appears to be the root cause of the graphical session failure. The compositor crashes immediately upon trying to allocate GPU memory.

```log
set 11 19:05:35 pop-os cosmic-comp[11171]: Error occured in main(): Backend creation failed
set 11 19:05:35 pop-os cosmic-comp[11171]: [EGL] 0x3003 (BAD_ALLOC) eglQueryDeviceAttribEXT
set 11 19:05:35 pop-os cosmic-comp[11171]: [EGL] 0x3003 (BAD_ALLOC) eglQueryDeviceAttribEXT
```

**2. `wireplumber` (Audio Subsystem) Failure**

This shows that the incompatible kernel is also failing to initialize audio hardware, indicating a wider driver issue.

```log
set 11 19:05:35 pop-os wireplumber[11160]: spa.alsa: can't open control for card 'NVidia_1': -2
set 11 19:05:35 pop-os wireplumber[11160]: spa.alsa: Card 'NVidia_1' can't get card info: No such file or directory
```

**3. `greetd` (Login Manager) Consequence**

This error is likely a symptom of the `cosmic-comp` crash, as the user session never starts successfully.

```log
set 11 19:05:35 pop-os greetd[11137]: gkr-pam: couldn't unlock the login keyring when trying to authenticate the user
```

**Comment by luanlouzada** [comment]
Fixed with sudo apt install nvidia-driver-580-open

**Comment by ottuzzi** [comment]
Same problem here but I was lucky and I detected the issue before rebooting.
Fixed with `sudo apt install nvidia-driver-580` (not open in my case to avoid adding more moving parts) followed by a `sudo dpkg --configure -a`

**Comment by effndc** [comment]
I wasn't so lucky, upgrading to 6.13 and the 580 driver just resulted in dependency failures and `dpkg --configure -a` failing to resolve issues.  Lost all graphics entirely, Nvidia drivers wouldn't load at all with the 6.13 kernel.  

Also tried to upgrade to 580 with the 6.12 kernel and lost graphics, it wouldn't load the rivers at all.  The 580 drivers seem problematic. 

This represents the worst upgrade experience I've ever seen on Linux, starting to regret having given Pop a try over other distributions.

**Comment by mmstick** [comment]
You need the 580 driver that was recently merged. It fixes the NVIDIA driver losing display out during the upgrade. To repair any NVIDIA packaging issue though, you can run `sudo apt purge ~nnvidia` to remove all NVIDIA packages. Reboot and then `sudo apt install nvidia-driver-580` to install the 580 driver anew. The NVIDIA driver would only lose display output if you were already running the previous unpatched driver.

**Comment by AlfonsoTovar** [comment]
i have a nvidia "GeForce GTX 1650 Ti Mobile" and it also fails, i tried to uninstall and reinstall and still fails
however the fix was
1. `sudo apt purge ~nnvidia`
2. `sudo apt autoremove`
3. `sudo apt install nvidia-driver-580`
4. reboot the system

BUT it not suppose that 

**nvidia-driver-580**: This is the standard NVIDIA driver from the Ubuntu/Pop OS repository (or NVIDIA's official package). It is a generic driver packaged for compatibility with Ubuntu-based systems.

**system76-driver-nvidia**: This is a custom driver maintained by System76, specifically tailored for their hardware and Pop OS. It includes additional integrations and optimizations for System76 devices

> So, from now on, should I use the unoptimized version of "nvidia-driver-580"?

Or should I try installing "system76-driver-nvidia" in a couple of weeks, once the issues have been resolved?

**Comment by arrrbeee** [comment]
I can confirm that upgrading to `nvidia-driver-580` then installing 6.16.3 kernel worked for me.

**Comment by Vladipz** [comment]
> I can confirm that upgrading to `nvidia-driver-580` then installing 6.16.3 kernel worked for me.

unfortunately I got a freeze and on 580.82.07 driver version
very sad I really thought this might fix my problem

**Comment by arrrbeee** [comment]
> > I can confirm that upgrading to `nvidia-driver-580` then installing 6.16.3 kernel worked for me.
> 
> unfortunately I got a freeze and on 580.82.07 driver version very sad I really thought this might fix my problem

Did you install in TTY? (Crtl-Alt-F3).

Also be sure to install `nvidia-dkms-580` as well.

**Comment by Vladipz** [comment]
> Did you install in TTY? (Crtl-Alt-F3).

I'll be honest, I'm not sure I understand what this means and how to do it. I do everything in this order: 
1. Completely Remove the Old Driver

This ensures a clean installation.

sudo apt purge '.*nvidia.*'
sudo apt autoremove

2. Update Your Package Lists

This will make your system aware of the newly released fixes.

sudo apt update

3. Install the New 580 Driver

This is the specific version the developer recommended for your hardware.

sudo apt install nvidia-driver-580

4. Reboot

sudo reboot

That guide was in #3579 

If you can help me with this I would be very grateful.

**Comment by Vladipz** [comment]
> Also be sure to install `nvidia-dkms-580` as well.

My system said :
```
nvidia-dkms-580 is already the newest version (580.82.07-1pop1~1757711639~22.04~edc5367).
nvidia-dkms-580 set to manually installed.
The following package was automatically installed and is no longer required:
  nvidia-firmware-575-575.64.05
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

**Comment by Vladipz** [comment]
> > > I can confirm that upgrading to `nvidia-driver-580` then installing 6.16.3 kernel worked for me.
> > 
> > 
> > unfortunately I got a freeze and on 580.82.07 driver version very sad I really thought this might fix my problem
> 
> Did you install in TTY? (Crtl-Alt-F3).
> 
> Also be sure to install `nvidia-dkms-580` as well.

I read a little and realized that this is something like a mode without an interface and no, I simply inserted it in the terminal while the graphics mode was enabled on the integrated

**Comment by Vladipz** [comment]
So what I should do wait for new update (if yes how to check and install) or what because i have thy a lot

**Comment by jo-jstrm** [comment]
For me, using the 6.16.3 kernel, `sudo apt purge ~nnvidia` and installing 580 afterwards did not work. I resorted to 470, which works. Not optimal of course, but good enough until we have a fix for 580.
