### ISSUE TITLE
Laptop won't turn on after closing lid

### ISSUE THREAD

**Issue by tmclea03** [pop-os/pop#522]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop! OS. Maybe Gnome-shell?

**Issue/Bug Description:**
Laptop won't wake after closing lid.

**Steps to reproduce (if you know):**
Close lid on laptop and allow time for it to go to low power. Open laptop, wait, try pressing keys/clicking/hitting power button and to no avail.

**Expected behavior:**
The laptop would power up into the Lock Screen

**Other Notes:**
ASUS Vivobook X505BA
CPU: AMD A9 9420 processor/gpu combo.
RAM: 8GB

**Comment by LeveyLeonhardt** [comment]
Same issue with ThinkPad P1 (Intel i7-8850H, Intel UHD 630 and NVIDIA Quadro P2000 Max-Q, 40GB RAM), although this issue only appears randomly: sometimes it resumes fine when I open the lid, but sometimes the laptop will simply not have any response. Pressing power button or any key won't resume the laptop either. The mute LED and power LED are on, so I know the laptop is on. When it fails to resume, journalctl won't have any log about the resuming event after I force-restart the laptop. I have this issue on both Pop!_OS 18.10 and 19.04, but it does happen less often with 19.04.

**Comment by ajfoster85** [comment]
Same issue here on Dell Latitude E7240 - sometimes when I close the laptop lid and re-open it I'm greeted with a black screen. Pressing the power button does nothing. Have also tried closing and re-opening the lid. It happens maybe one time in every 3 or 4 but seems random. Running pop_os! version 19.04.

**Comment by ajfoster85** [comment]
Is this something to do with swap space? I've noticed that mine seems to do it if I leave the laptop for a long time and it goes into hibernation. I let the Pop_OS! installer decide on the sizes of all the partitions but I've noticed it has only allocated 4GB of swap. If hibernation is being used Ubuntu (which Pop_OS! is based on) recommends a swap size of your RAM size plus the square root of RAM size - so for me with 8GB of RAM that would be 11GB.

**Comment by ajfoster85** [comment]
After installing 18.04 (see above) I followed the advice in the ticket [here](https://github.com/pop-os/pop/issues/349) and it hasn't happened since - might be a coincidence but could be worth a try?

**Comment by tmclea03** [comment]
That didn't seem to fix my issue. Still a blank screen when opening the lid.

**Comment by mmstick** [comment]
This is something we have no control over, since it's hardware-specific.

**Comment by ajfoster85** [comment]
> That didn't seem to fix my issue. Still a blank screen when opening the lid.

Yeah it started doing it again on my machine too - right after I posted my comment!

**Comment by tmclea03** [comment]
I find it strange that it is considered hardware specific when it worked just fine in Ubuntu. If you are using a forked version of Ubuntu, wouldn't that mean it was a change made by the Pop! OS team? Or maybe a driver that your team didn't include?

**Comment by mmstick** [comment]
@tmclea03 We use the same kernel, and therefore the same drivers.

**Comment by tmclea03** [comment]
After some heavy digging, it seems like the issue is one with the Linux kernel and Mesa with AMD GPUs. This issue didn't exist in 4.20 so my solution to those with AMD cards having the issue would be to roll back to the 4.20 kernel. I'm going to close this issue here as my problem is solved.

**Comment by saravenpi** [comment]
I've got the exact same issue on my Asus TUF

**Comment by stephenaustin** [comment]
Asus Zenbook with Pop OS 22.04, Kernel 6.9.3-76060903- Generic. Exactly the same problem. Have marauded around endless tech sites trying to find a fix. Only thing I can do is avoid putting the lid down and just shut down. 

Interesting to see if the new Cosmic fixes this.

**Comment by ntua-el19096** [comment]
Same issue on Levono Legion Y540, kernel version: 6.9.3-76060903-generic (was happening also in 5.x versions), pop-os 22.04.

It does not always happen but I still can't figure out when it happens and when not. If the time that passes between suspension and resume is small (haven't figured out in the order of what), it does not seem to happen that often.
When it resumes one of the following might happen:

- Black screen only with working backlight
- Lock Screen with working cursor, unresponsive keyboard and unclickable GUI
- Last thing the display was showing but with unresponsive GUI (with or without working cursor)
