### ISSUE TITLE
Copy and Paste unreliable after recent Mutter upgrade

### ISSUE THREAD

**Issue by dhitchcock** [pop-os/pop#819]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
mutter:
  Installed: 3.34.1+git20191107-1ubuntu1~19.10.1
  Candidate: 3.34.1+git20191107-1ubuntu1~19.10.1pop0~1577373981~19.10~c905911
  Version table:
     3.34.1+git20191107-1ubuntu1~19.10.1pop0~1577373981~19.10~c905911 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
 *** 3.34.1+git20191107-1ubuntu1~19.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.34.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
```

**Issue/Bug Description:**

After the most recent update of mutter to copy and pasting would fail about 50% of the time.  I downgraded back to `3.34.1+git20191107-1ubuntu1~19.10.1` and the problem went away.  I suspect it's a manifest of this bug:

https://gitlab.gnome.org/GNOME/mutter/issues/878#note_642048

**Steps to reproduce (if you know):**
upgrade mutter to `3.34.1+git20191107-1ubuntu1~19.10.1pop0~1577373981~19.10~c905911`, copy and paste a couple times.  Sometimes it works, sometimes it don't.

**Expected behavior:**
It'd copy and paste reliably!

**Other Notes:**
In the mean time I created a file in /etc/apt/preferences.d containing
```
Package: mutter
Pin: version 3.34.1+git20191107-1ubuntu1~19.10.1pop0~1577373981~19.10~c905911
Pin-Priority: 99
```
to keep it off my system.

**Comment by mmstick** [comment]
The issue you linked states that this is an issue only in Wayland, and is fixed by a recent git version of GTK. Are you using Wayland? If so, I'd really recommend to switch back to X11, because Wayland GNOME session still has a lot of issues.

**Comment by dhitchcock** [comment]
I am not using Wayland.  In the comments are a couple others who chimed in they have the problem in Xorg.  Doesn't really matter much though if that's NOT the bug, just threw that link in there for FYI.  But downgrading mutter definitely eliminated the problem for me, which is good I was about to wipe Pop it was so infuriating, but with the downgrade I can use my machine again without screaming :-D

**Comment by mmstick** [comment]
That would be strange, since I have all updates on all of my systems, and have no issue with copy and paste on any of them.

**Comment by dhitchcock** [comment]
Shoot, sorry, close this issue.  I absolutely still have this problem, but my culprit and solution are bupkis.  I switched mutter package, and rebooted, and the problem was gone, so I patted myself on back.  But it's back this morning, on rolled back mutter, and I've found the real culprit --> Gnome Boxes.  I have a Gnome Boxes vm running Fedora open, not in focus or involved in the copy/paste at all, just background running on a different desktop.  I shut that off, problem gone.
