### ISSUE TITLE
System Suspends on lid-close even while external display attached

### ISSUE THREAD

**Issue by jlacroix82** [pop-os/pop#82]
* Distribution - Ubuntu 17.10/PopOS 17.10)

When the laptop lid is closed (Galago UltraPro) the laptop will suspend, even with an external display/AC adapter attached. The preferred behavior is that the laptop shouldn't suspend when it's plugged in to an external monitor.

On a fresh boot, this doesn't seem to happen. If I boot with the lid closed and an external display attached, it will not suspend. However, if I disconnect the HDMI cable, put the laptop to sleep manually and then wake it up, it will start suspending each time the lid is closed, whether or not a display is attached. This makes using the laptop at my desk virtually impossible. I need to reboot it each time I wish to regain the preferred behavior.

I tested this and was able to reproduce this with both Ubuntu 17.10, as well as Pop-OS 17.10 in live mode.

**Steps to reproduce**
* Attach an external display (I connected via standard HDMI)
* Close the lid
* The laptop will suspend
* If the laptop doesn't suspend, put the laptop to sleep manually, wake it up, repeat and this will start happening
* Reboot with the external display attached and the lid closed, note there is no issue

**Expected behavior**
Laptops should not suspend if the lid is closed and an external display is attached. Many people (like myself) use their laptop as both a desktop and a laptop. At home, it's docked and used as a desktop. But I often take it with me to coffee shops, etc for outside use. If the laptop suspends when the lid is closed, it makes using it with an external display impossible unless you keep the laptop lid open.

**Other Notes**
I tried modifying the gconf settings at the following location:
/org/gnome/settings-daemon/plugins/power/
These settings are all ignored. It doesn't matter what you set them to, it does not fix it. You can configure keys such as "lid-close-ac-action" and "lid-close-suspend-with-external-monitor" to configure what GNOME should do when these events occur, but these settings are ignored.

I also tried configuring the lid switch events at /etc/systemd/logind.conf but these settings also have no affect. It's almost as if something else is overriding both GNOME and Systemd's handling of the lid close event.

**Comment by ahoneybun** [comment]
Thank you for filling this issue to make Pop!_OS better! I'm going to test the dconf changes you have made as well in the lab.

**Comment by WatchMkr** [comment]
I thought we addressed this bug a while ago. Currently, when I close the lid with and external monitor attached, the laptop stays awake. @brs17 do you recall this one?

I'll add the needs testing tag and hopefully someone can help confirm the bug - or we can figure out if it's a settings problem.

**Comment by jlacroix82** [comment]
So far this is working for me, I am not sure what changed. It last did this a few weeks ago. I'll let you know if it happens again.

**Comment by WatchMkr** [comment]
Thanks, Jay. We'll close for now.

**Comment by jlacroix82** [comment]
Unfortunately, this bug is back for me. It's really hard to use my laptop with an external monitor, keyboard, and mouse. To reproduce, I had my laptop disconnected from my external display for a while, then I returned to my desk, plugged in the AC adapter, the external display, and then closed the lid. The laptop went to sleep. It shouldn't have went to sleep, since the default for GNOME is to not suspend while the lid is closed when an external display is attached. That's the desired behavior. This was working fine for a while but as of this week I am suffering form this again. I am currently using Xorg, and the HiDPI damon is currently disabled if that matters.

**Comment by vycoder** [comment]
Having the same issues. I thought I didn't, just noticed that my laptop screen has a subtle burn in the middle. I had my Dell XPS 15 laptop tucked away under my desk when working that's why I didn't notice.
